version: '3.8'
services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  publisher:
    build: ./docker/publisher
    depends_on:
      - broker

  processor:
    build: ./docker/processor
    depends_on:
      - broker

  subscriber:
    build: ./docker/subscriber
    depends_on:
      - processor
