version: '3.8'
services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    

  publisher:
    build:
      context: .
      dockerfile: docker/publisher/Dockerfile
    depends_on:
      - broker

  processor:
    build:
      context: .
      dockerfile: docker/processor/Dockerfile
    depends_on:
      - broker
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=1883

  subscriber:
    build:
      context: .
      dockerfile: docker/subscriber/Dockerfile
    depends_on:
      - processor
