name: Deploy Script
on:
  push:
    branches: [ "feature-Docker" ]
    
jobs:
  test-and-deploy:
    runs-on: self-hosted  # Uses EC2 runner!
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: python3 -m pytest testing/test_processor.py -v

      - name: Backup & Deploy the app
        if: success()
        run: |
          # Rename old file (add date)
          mv ~/stream_processor.py ~/stream_processor_$(date +'%Y-%m-%d').py
          # Copy new file 
          cp ./stream_processor.py ~/stream_processor.py